name: Docker image build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build & Push Image
        run: |
          echo "${{ secrets.DOCKERTOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t "${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest" .
          docker push "${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest"
    
